// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace banco_api.Domain.Models;

public partial class Account
{
    public string Id { get; set; }

    public string AccountTypeId { get; set; }

    public string ClientId { get; set; }

    public string AccountNumer { get; set; }

    public decimal? InitialBalance { get; set; }

    public bool? Status { get; set; }

    public virtual AccountType AccountType { get; set; }

    public virtual Client Client { get; set; }

    public virtual ICollection<Movement> Movements { get; set; } = new List<Movement>();
}