// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace banco_api.Domain.Models;

public partial class Client
{
    public string Id { get; set; }

    public string PersonId { get; set; }

    public string Password { get; set; }

    public bool? Status { get; set; }

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();

    public virtual Person Person { get; set; }
}