// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace banco_api.Domain.Models;

public partial class Movement
{
    public string Id { get; set; }

    public string AccountId { get; set; }

    public DateTime? Date { get; set; }

    public string MovementType { get; set; }

    public decimal? Value { get; set; }

    public decimal? Balance { get; set; }

    public virtual Account Account { get; set; }
}