// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace banco_api.Domain.Models;

public partial class Person
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Gender { get; set; }

    public int? Age { get; set; }

    public string Credential { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public virtual ICollection<Client> Clients { get; set; } = new List<Client>();
}